sudo: required
services:
  - docker 

before_install:
  - docker build -t raulla/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true raulla/react-test npm test -- --coverage

after_success:
  - docker build -t raulla/multi-client ./client
  - docker build -t raulla/multi-nginx ./nginx
  - docker build -t raulla/multi-server ./server
  - docker build -t raulla/multi-worker ./worker
  #docker-login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #publish 
  - docker push raulla/multi-client
  - docker push raulla/multi-nginx
  - docker push raulla/multi-server
  - docker push raulla/multi-worker